services:

  postgres:
    image: postgres:15
    container_name: cuma-admin-database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "1212:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    mem_limit: 1024m
    cpus: 1.0
    networks:
     - CUMA-admin

  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuma-admin
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6060:8080"
    networks:
      - CUMA-admin

networks:
  CUMA-admin:
    external: true